### ISSUE TITLE
0.9.0 does not work anymore on VS community 2017

### ISSUE THREAD

**Issue by TeoMan** [GordianDotNet/VSMonoDebugger#11]
After last update 0.9.0, the packages does not work anymore vith VS 2017 community version 15.0.0+26228.86
It does not open the setting page, does not deploy, and so on.

I reinstalled the 0.8.0 package contained in the MarketplaceReleases folder an everyhing started working again

**Comment by GordianDotNet** [comment]
To support AsyncPackage in Visual Studio 2019, I upgraded Microsoft.VisualStudio.CoreUtility from 15.0.26201 to 15.0.26606 during development. The reason was a reference to Microsoft.VisualStudio.Shell.Interop.15.3.DesignTime.

But I just downgraded all nuget packages and there are no build errors. Apparently I solved the problem differently during further development.

I will test it again and then release a new version if there are no problems. However, I can't get a 15.0.x from Visual Studio 2017 anymore. Do you know any possibilities here?

Question: What are the reasons why you are not upgrading Visual Studio from 15.0 to 15.9?

**Comment by TeoMan** [comment]
Thanks for your work!!
To download versione 15.0 I connected to MyVisualStudio on Microsoft website in the Download area:
https://my.visualstudio.com/Downloads/Featured

I selected on the bottom Visual Studio 2017 and in the list I have both 15.0 and 15.9 available for download. 
Latest update for 15.0 is today (11 jun 2019)

I need 15.0 because in our office we have to mantain several .NET 2.0 softwares and with 15.9.9 we had errors compiling libraries (msbuild tells something like "dll built against the wrong framework version", I think it is one interop ocx dll that gives this error).
We have not tried to use the latest 15.9 version anyway...

**Comment by dhanarfmlx** [comment]
Hi,

I probably encounter the same issue. I am using VS2017 15.9.12.

After extension upgraded to 0.9.0, I can deploy but somehow the debug session is not started properly. The output window on my VS2017 usually shows the console output of application being debugged, but now I have no output at all. It is like the remote debugging session never connected.

I can confirm that downgrading to version 0.8.0 and disable auto update, I can deploy and debug again.

**Comment by GordianDotNet** [comment]
I tested it with Visual Studio 2017 15.9.13 and found no issues. 
Could you please provide the logs?

**Comment by GordianDotNet** [comment]
I released V0.9.3 with the old references from v0.8.0. I hope it will fix the errors. If not I need a log file.

@dhanarfmlx  "missing console output" was an additional bug. Thanks!

**Comment by dhanarfmlx** [comment]
@GordianDotNet I upgraded to v0.9.3 and I can confirm that I can deploy and debug normally.

Thank you!

**Comment by TeoMan** [comment]
Hello
I confirm you that now everything is working correctly.
Thanks
