### ISSUE TITLE
Update for VS2022 and .NET 6

### ISSUE THREAD

**Issue by DamianSuess** [GordianDotNet/VSMonoDebugger#28]
Let me open by saying, wonderful extension, thank you!

Is there any chance this can be updated for VS2022 and include the ability to debug the latest .NET?  There are instances where WSL2 just doesn't cut it (_i.e. debugging Bluetooth LE interfaces_) and I require the use of a remote Linux machine. Currently, with VS2022, I have to build, copy/paste the output to the machine, run it manually and then attach to the process via SSH, and hope I didn't miss my breakpoint.

Unfortunately, I'm on a newer version of Visual Studio and using .NET 5 and 6, not Mono anymore.

I'd like to take a crack at adding those capabilities, but currently don't have the bandwidth to do so.

**Comment by haijunluo** [comment]
I'm following you, hope you can update [VsLinuxDebug](https://github.com/SuessLabs/VsLinuxDebug)

**Comment by GordianDotNet** [comment]
I created a new VSMonoDebugger2022 version to support VS2022 today. I also don't use Mono anymore. But I needed an extension for the .NET 5 and 6 deployment via SSH. Unfortunately, VsLinuxDebug didn't work because the device doesn't have curl installed and also doesn't have access to the internet. So I have to install VSDebugger manually.
After that I use the Visual Studio 2022 SSH Remote Debugger.

Maybe I can extend the extension VSMonoDebugger2022 for a better dotnet debugging workflow. Unfortunately, I usually don't have the time to do so.

**Comment by DamianSuess** [comment]
Gteat update @GordianDotNet! So the cURL auto-installer wasn't working? Odd, I'll check into it. None the less, I really appreciate your tool as you inspired me to create the VSLinuxDebug. Keep up the great work. If we bump into each other at a future tech conference, beers are on me 👍
