### ISSUE TITLE
VSMonoDebugger will not install on latest VS2019 release 16.11.17

### ISSUE THREAD

**Issue by oznetmaster** [GordianDotNet/VSMonoDebugger#31]
[dd_VSIXInstaller_20220720173558_2940c.log](https://github.com/GordianDotNet/VSMonoDebugger/files/9152161/dd_VSIXInstaller_20220720173558_2940c.log)

I have attached the VSIX Installer log from the installation failure.

**Comment by GordianDotNet** [comment]
Sorry, but you have a strange Visual Studio 2019 installation path: 
`Unable to load extension at: D:\DEVELOPMENT (X86)\MICROSOFT VISUAL STUDIO\2019\ENTERPRISE\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\WEBCLIENT\DIAGNOSTICS\CHROMEDEBUGADAPTER\`

The log has a lot of errors for all possible other extensions because the installation path D:\DEVELOPMENT (X86)\MICROSOFT VISUAL STUDIO\2019\ENTERPRISE leads to errors.
I cannot reproduce this error. The installation process is handled by Visual Studio. I can't influence that.

**Comment by oznetmaster** [comment]
That is the path for a long time.  VSMonoDebugger worked fine with that path prior to the latest update of VS2019.  Nothing strange about the path.  ALL other extension work perfectly, and there are a lot of them.  The problem is definitely with your code.
